# Use an official Python runtime as a parent image
FROM python

# Set the working directory to /app
WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
